pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/venkatesh2608/newrepo.git'
            }
        }
        stage('Build') {
            steps {
                dir('demo') {
                    bat 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('demo') {
                    bat 'mvn test'
                }
            }
        }
        stage('Reports') {
            steps {
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'target/surefire-reports/Playwright Suite',
                    reportFiles: 'index.html',
                    reportName: 'Playwright Test Report'
                ])
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/target/surefire-reports/Playwright Suite/Headless Browser Automation.html'
        }
    }
}
